# shapes[{}].label)
shapes[0].mesh.show()
# shapes[{}].label)
shapes[1].mesh.show()
# shapes[{}].label)
shapes[2].mesh.show()
# shapes[{}].label)
shapes[3].mesh.show()
# shapes[{}].label)
shapes[4].mesh.show()
# shapes[{}].label)
shapes[5].mesh.show()
# shapes[{}].label)
shapes[6].mesh.show()
# shapes[{}].label)
shapes[7].mesh.show()
# shapes[{}].label)
shapes[8].mesh.show()
# shapes[{}].label)
shapes[9].mesh.show()
# shapes[{}].label)
shapes[10].mesh.show()
# shapes[{}].label)
shapes[11].mesh.show()
# shapes[{}].label)
shapes[12].mesh.show()
# shapes[{}].label)
shapes[13].mesh.show()
# shapes[{}].label)
shapes[14].mesh.show()
# shapes[{}].label)
shapes[15].mesh.show()
# shapes[{}].label)
shapes[16].mesh.show()
# shapes[{}].label)
shapes[17].mesh.show()
# shapes[{}].label)
shapes[18].mesh.show()
# shapes[{}].label)
shapes[19].mesh.show()
# shapes[{}].label)
shapes[20].mesh.show()
# shapes[{}].label)
shapes[21].mesh.show()
# shapes[{}].label)
shapes[22].mesh.show()
# shapes[{}].label)
shapes[23].mesh.show()
# shapes[{}].label)
shapes[24].mesh.show()
# shapes[{}].label)
shapes[25].mesh.show()
# shapes[{}].label)
shapes[26].mesh.show()
# shapes[{}].label)
shapes[27].mesh.show()
# shapes[{}].label)
shapes[28].mesh.show()
# shapes[{}].label)
shapes[29].mesh.show()
# shapes[{}].label)
shapes[30].mesh.show()
# shapes[{}].label)
shapes[31].mesh.show()
# shapes[{}].label)
shapes[32].mesh.show()
# shapes[{}].label)
shapes[33].mesh.show()
# shapes[{}].label)
shapes[34].mesh.show()
# shapes[{}].label)
shapes[35].mesh.show()
# shapes[{}].label)
shapes[36].mesh.show()
# shapes[{}].label)
shapes[37].mesh.show()
# shapes[{}].label)
shapes[38].mesh.show()
# shapes[{}].label)
shapes[39].mesh.show()
# shapes[{}].label)
shapes[40].mesh.show()
# shapes[{}].label)
shapes[41].mesh.show()
# shapes[{}].label)
shapes[42].mesh.show()
# shapes[{}].label)
shapes[43].mesh.show()
# shapes[{}].label)
shapes[44].mesh.show()
# shapes[{}].label)
shapes[45].mesh.show()
# shapes[{}].label)
shapes[46].mesh.show()
# shapes[{}].label)
shapes[47].mesh.show()
# shapes[{}].label)
shapes[48].mesh.show()
# shapes[{}].label)
shapes[49].mesh.show()
# shapes[{}].label)
shapes[50].mesh.show()
# shapes[{}].label)
shapes[51].mesh.show()
# shapes[{}].label)
shapes[52].mesh.show()
# shapes[{}].label)
shapes[53].mesh.show()
# shapes[{}].label)
shapes[54].mesh.show()
# shapes[{}].label)
shapes[55].mesh.show()
# shapes[{}].label)
shapes[56].mesh.show()
# shapes[{}].label)
shapes[57].mesh.show()
# shapes[{}].label)
shapes[58].mesh.show()
# shapes[{}].label)
shapes[59].mesh.show()
# shapes[{}].label)
shapes[60].mesh.show()
# shapes[{}].label)
shapes[61].mesh.show()
# shapes[{}].label)
shapes[62].mesh.show()
# shapes[{}].label)
shapes[63].mesh.show()
# shapes[{}].label)
shapes[64].mesh.show()
# shapes[{}].label)
shapes[65].mesh.show()
# shapes[{}].label)
shapes[66].mesh.show()
# shapes[{}].label)
shapes[67].mesh.show()
# shapes[{}].label)
shapes[68].mesh.show()
# shapes[{}].label)
shapes[69].mesh.show()
# shapes[{}].label)
shapes[70].mesh.show()
# shapes[{}].label)
shapes[71].mesh.show()
# shapes[{}].label)
shapes[72].mesh.show()
# shapes[{}].label)
shapes[73].mesh.show()
